### ISSUE TITLE
undefined reference to `xcb_total_read'

### ISSUE THREAD

**Issue by asgh** [Zirias/xmoji#5]
```
Also some warnings:

   [CC]   obj/i686-linux-gnu/release/src/bin/xmoji/font.o
src/bin/xmoji/font.c: In function ‘createFromFile’:
src/bin/xmoji/font.c:229:45: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘FT_Long’ {aka ‘long int’} [-Wsign-compare]
     while ((face->num_glyphs & glyphidmask) != face->num_glyphs)

   [CC]   obj/i686-linux-gnu/release/src/bin/xmoji/x11adapter.o
src/bin/xmoji/x11adapter.c: In function ‘readX11Input’:
src/bin/xmoji/x11adapter.c:508:25: warning: implicit declaration of function ‘xcb_total_read’; did you mean ‘xcb_host_end’? [-Wimplicit-function-declaration]
     uint64_t newrdpos = xcb_total_read(c);
                         ^~~~~~~~~~~~~~
                         xcb_host_end
src/bin/xmoji/x11adapter.c: In function ‘flushandsync’:
src/bin/xmoji/x11adapter.c:599:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘uint64_t’ {aka ‘long long unsigned int’} [-Wsign-compare]
  while (xcb_total_read(c) != rdpos)
                           ^~
src/bin/xmoji/x11adapter.c:619:32: warning: comparison of integer expressions of different signedness: ‘int’ and ‘uint64_t’ {aka ‘long long unsigned int’} [-Wsign-compare]
     } while (xcb_total_read(c) != rdpos);
                                ^~

   [CCLD] bin/i686-linux-gnu/release/xmoji
/usr/bin/ld: obj/i686-linux-gnu/release/src/bin/xmoji/x11adapter.o: in function `readX11Input':
x11adapter.c:(.text.readX11Input+0x1b): undefined reference to `xcb_total_read'
/usr/bin/ld: x11adapter.c:(.text.readX11Input+0x1c8): undefined reference to `xcb_total_read'
/usr/bin/ld: obj/i686-linux-gnu/release/src/bin/xmoji/x11adapter.o: in function `flushandsync':
x11adapter.c:(.text.flushandsync+0x42): undefined reference to `xcb_total_read'
/usr/bin/ld: x11adapter.c:(.text.flushandsync+0xc5): undefined reference to `xcb_total_read'
/usr/bin/ld: obj/i686-linux-gnu/release/src/bin/xmoji/x11adapter.o: in function `X11Adapter_init':
x11adapter.c:(.text.X11Adapter_init+0xc12): undefined reference to `xcb_total_read'
collect2: error: ld returned 1 exit status
make[1]: *** [src/bin/xmoji/xmoji.mk:103: bin/i686-linux-gnu/release/xmoji] Error 1
make: *** [zimk/lib/platform.mk:25: all] Error 2

```

**Comment by Zirias** [comment]
Unfortunately, `xcb_total_read()` is a hard requirement for reliably integrating xcb in an outer event loop without dedicating an extra thread to it (like many toolkits do). Of course it should check for the minimum required xcb version instead of failing at compile time, I will fix that ...

**Comment by asgh** [comment]
I'm in the process of doing a series of upgrades to my machine (I wasn't able to for a long time due to insufficient disk space).

So you get the benefit of testing your code on old distributions :)

Looks like next upgrade xcb will be new enough, hopefully in the next couple weeks.

**Comment by Zirias** [comment]
> So you get the benefit of testing your code on old distributions :)

And if possible, I'm happy to keep my code compatible with older libs and tools. Here it's not possible (without radically changing the design) unfortunately, but at least it should not just fail at build time...

> Were the warnings anything important?

The first one is interesting, I assume you build on a 32bit platform? On Linux-x86, `long` and `uint32_t` have the same size, and then, the bitwise and is done on operands converted to unsigned, leading to the warning comparing the result to a signed value. On most 64bit ABIs, `long` also has 64 bits, therefore the bitwise and is implicitly done signed and no warning occurs, that's why my CI build doesn't catch it.

It shouldn't break anything in practice (POSIX mandates exact-width types which imply two's-complement representation, so comparisons should be well-defined), but I'll still add an explicit cast to silence the warning 🙂

The other two warnings are just fallout from the missing function, the compiler assumes the old "implicit int" rule for them.
